version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: highlight.js
    versions:
    - 10.5.0
  - dependency-name: hexo
    versions:
    - 5.3.0
