# Header link with icon font awesome (fa-icon : link)
# name auto font awesome
menu:
  Home: /
  Archive: /archives
  Info: /about

grid: 2 # change index columns /line
gravatar: berlinchancom@gmail.com #img gravatar in post
excerpt_link: 解说 #chnge text in read more in index
thumbimg : img/default-thumb.svg # default img (thumbail post) if post no image

## more need change
disqus_shortname: old-site-museum
google_analytics: UA-43244265-4

# if u want add more profile media social (icon same as Fontawesome)
#  just add name ex : Instagram: https://www.instagram.com/you/
social:
  Twitter: https://twitter.com/BerlinChanCom
  Facebook: https://facebook.com/berlinchancom
  LinkedIn: https://www.linkedin.com/in/berlinchan
  Github: https://github.com/BerlinChan
  Youtube: https://www.youtube.com/user/berlinchancom
  email: berlinchancom@gmail.com
  # Instagram: https://www.instagram.com/you/

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties
